<table>
    <tr>
        <td><img src="https://s3.amazonaws.com/media-p.slid.es/uploads/1485763/images/9060062/Header.png" width="300"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue">  Conceptos  </p>  Bag of Words   </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">PLN </p></tp>
            <tp><p style="font-size:115%;text-align:center">Pregrado MACC 2023-2</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

A continuación revisaremos rápidamente algunos conceptos claves en el desarrollo de procesamiento de lenguaje natural.

<FONT SIZE=3 COLOR="blue"> **Normalización** </FONT> Es una etapa en el Procesamiento de Lenguaje Natural donde se busca poner todo el texto en igualdad de condiciones, es decir, todo en el mismo tipo de letra , eliminar signos de puntuación, quitar palabras, etc. En otras palabras limpiamos el texto para aplicar algunos modelo o técnicas al mismo.

<FONT SIZE=3 COLOR="blue"> **Tokenización** </FONT>: Es el proceso de dividir las cadenas de texto de un documento en piezas más pequeñas que se denominan *tokens*.

<FONT SIZE=3 COLOR="blue"> **Stemming:** </FONT>: Es la tarea en procesamiento de lenguaje natural de eliminar: sufijos, prefijos, etc. para obtener el tallo de la palabra:

- Caminando : caminar

- Anteriormente: anterior

<FONT SIZE=3 COLOR="blue"> **Lematización:** </FONT> es el proceso en el que se identifica y sustituye una palabra (plurales, femeninos, conjugaciones, etc) por su *lema* (raíz). Esto quiere decir por una palabra qe sea válida en el idioma.

- Carros : Carro

- Comiendo : comer

- Entrenaría : entrenar

<FONT SIZE=3 COLOR="blue"> **Part of Speech (PoS)-Tagging:** </FONT> Proceso mediante el cual se asigna una etiqueta de categoría a las partes tokenizadas de una oración. Es decir, si es sustantivo, verbo, etc.

    - Artículo o determinante: un, el, las
    - Sustantivo o nombre: hombre, tren, carro, mueble
    - Pronombre: yo, tu, el, ella  
    - Verbo: correr, pensar --acción
    - Adjetivo: alto, valente, nuevo.
    - Adverbio: tarde, temprano, anoche, constantemente.
    - Preposición: a, ante, con , contra, (unir palabras)
    - Conjunción: y, o, ni, que
    - Interjección: ¡ay! ,¡oh! (sentimiento)

<FONT SIZE=3 COLOR="blue"> **n-grammas:** </FONT> modelo de representación para simplificar los contenidos de un texto. En los n-gramas nos interesa preservar secuencias contiguas de N-elementos de la selección de texto.

<FONT SIZE=3 COLOR="blue"> **Stop Words:** </FONT> Son palabras que no aportan al significado de la oraciones : preprosiciones, conjunciones, adverbios, artículos, etc.

Veamos algunos ejemplos de lo anterior. Para ello vamos a importar la librería *nltk*

In [ ]:
import nltk
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

# <FONT SIZE=4 COLOR="purple"> 1. tokenizar </FONT>

In [ ]:
# separa cuando encuentra espacio
documento1 = "Cien años! de sole.dad 100.56 es una novela del escritor colombiano\
Gabriel García Márquez, ganador del Premio Nobel de Literatura en 1982.\
Es considerada una obra maestra? de la literatura hispanoamericana y universal.\
Así como una de las obras más traducidas y leídas en español."
words = nltk.word_tokenize(documento1)
print(words)

['Cien', 'años', '!', 'de', 'sole.dad', '100.56', 'es', 'una', 'novela', 'del', 'escritor', 'colombianoGabriel', 'García', 'Márquez', ',', 'ganador', 'del', 'Premio', 'Nobel', 'de', 'Literatura', 'en', '1982.Es', 'considerada', 'una', 'obra', 'maestra', '?', 'de', 'la', 'literatura', 'hispanoamericana', 'y', 'universal.Así', 'como', 'una', 'de', 'las', 'obras', 'más', 'traducidas', 'y', 'leídas', 'en', 'español', '.']


# <FONT SIZE=4 COLOR="purple"> 2. Stemming </FONT>

- Funciona mejor para inglés

In [ ]:
from nltk.stem import PorterStemmer
stm = PorterStemmer()

In [ ]:
print(stm.stem('running'))
print(stm.stem('minimum'))
print(stm.stem('likely'))

run
minimum
like


Con la siguiente librería podemos usar otros idiomas. Pero dado que *nltk* está enfocado al inglés, funciona mejor con estos idiomas.

In [ ]:
from nltk.stem.snowball import SnowballStemmer

In [ ]:
print(" ".join(SnowballStemmer.languages))

arabic danish dutch english finnish french german hungarian italian norwegian porter portuguese romanian russian spanish swedish


In [ ]:
stemmer = SnowballStemmer("spanish")

In [ ]:
print(stemmer.stem("precisamente"))
print(stemmer.stem("increible"))

precis
increibl


# <FONT SIZE=4 COLOR="purple"> 3. Stop Words </FONT>



In [ ]:
from nltk.corpus import stopwords
print(set(stopwords.words('spanish')))

{'tuvo', 'vuestros', 'tenido', 'tendremos', 'tendrán', 'sea', 'fuisteis', 'éramos', 'vuestra', 'otro', 'estamos', 'esté', 'entre', 'me', 'hubisteis', 'con', 'tuvieron', 'estada', 'ha', 'por', 'un', 'eso', 'son', 'hubieran', 'soy', 'estarías', 'mías', 'donde', 'algunos', 'estemos', 'todo', 'esta', 'vuestro', 'o', 'habrán', 'hubiste', 'serían', 'fueron', 'hubiesen', 'estuviese', 'tuviésemos', 'han', 'y', 'sintiendo', 'suya', 'estéis', 'fuese', 'fuerais', 'habiendo', 'nosotras', 'habían', 'estos', 'nuestras', 'tuvieseis', 'tienes', 'estuvo', 'están', 'algunas', 'tuvimos', 'todos', 'ellas', 'sois', 'le', 'estuviésemos', 'tengáis', 'lo', 'hay', 'haya', 'hemos', 'nada', 'estuviesen', 'estas', 'estábamos', 'estuvisteis', 'otras', 'habréis', 'tendréis', 'sus', 'otra', 'estuvieses', 'vosotros', 'estaría', 'estarían', 'serías', 'tuviesen', 'muchos', 'el', 'habrás', 'estuvieran', 'les', 'estad', 'seamos', 'tuyo', 'estaban', 'habías', 'fuera', 'nosotros', 'habéis', 'fueran', 'estuvieseis', 'fuesen

In [ ]:
doc = "Un radar multa a Fabian Sanchez por conducir demasiado rapido en la autopista"
words = nltk.word_tokenize(doc)
for word in words:
        if word in stopwords.words('spanish'):
            print (word)

a
por
en
la


# <FONT SIZE=4 COLOR="purple"> 4. Lematización </FONT>

In [ ]:
from nltk.stem import WordNetLemmatizer
lemm = WordNetLemmatizer()

In [ ]:
print(lemm.lemmatize('dogs'))
print(lemm.lemmatize('houses'))
print(lemm.lemmatize('perros'))


dog
house
perros


# <FONT SIZE=4 COLOR="purple"> 5. n-grams </FONT>

Los **n-gram** son un modelo de representación que selecciona secuencias contiguas de *n*-elementos del texto

- Veamos un ejemplo

In [ ]:
from nltk import ngrams


In [ ]:
doc = "Un radar multa a Fabian Sanchez por conducir demasiado rapido en la autopista"
words = nltk.word_tokenize(doc)
num_elementos = 3
n_grams = ngrams(words, num_elementos)
for grams in n_grams:
    print (grams)

('Un', 'radar', 'multa')
('radar', 'multa', 'a')
('multa', 'a', 'Fabian')
('a', 'Fabian', 'Sanchez')
('Fabian', 'Sanchez', 'por')
('Sanchez', 'por', 'conducir')
('por', 'conducir', 'demasiado')
('conducir', 'demasiado', 'rapido')
('demasiado', 'rapido', 'en')
('rapido', 'en', 'la')
('en', 'la', 'autopista')


<FONT SIZE=4 COLOR="purple"> 6. Etiquetado Formológico- PoS (part of speech-tagging) </FONT>

NLTK nos da algunas herramientas para crear etiquetadores morfológicos, es decir, identificar si una palabra es verbo, sustantivo, adjetivo , etc.

CC : coodinate conjunction

CD : cardinal number

DT : determiner

EX ; existencial there

FW : foeign word

IN : preprosition or subordinating

JJ : adjetive

JJR : adjetive, comparative

JJS : adjetive superlative
...
BV : verbo forma base

VBD : verbo pasado

VBG : verb gerundio

Para mayor información ver

[TAGGING](https://pythonspot.com/nltk-speech-tagging/)

Usaremos **nltk.pos_tag** que es un etiquetador morfológico basado en aprendizaje automático. A partir de miles de ejemplos de oraciones etiquetadas manualmente, el sistema *ha aprendido*, calculando frecuencias y generalizando cuál es la categoría gramatical más probable para cada token.

In [ ]:
oracion1 = "This is the lost dog I found at the park".split()
oracion2 = "The progress of the humankind as I progress".split()
oracion3 = "When I went to the University, I played soccer".split()
print(nltk.pos_tag(oracion1))
print(nltk.pos_tag(oracion2))
print(nltk.pos_tag(oracion3))

[('This', 'DT'), ('is', 'VBZ'), ('the', 'DT'), ('lost', 'JJ'), ('dog', 'NN'), ('I', 'PRP'), ('found', 'VBD'), ('at', 'IN'), ('the', 'DT'), ('park', 'NN')]
[('The', 'DT'), ('progress', 'NN'), ('of', 'IN'), ('the', 'DT'), ('humankind', 'NN'), ('as', 'IN'), ('I', 'PRP'), ('progress', 'VBP')]
[('When', 'WRB'), ('I', 'PRP'), ('went', 'VBD'), ('to', 'TO'), ('the', 'DT'), ('University,', 'NNP'), ('I', 'PRP'), ('played', 'VBD'), ('soccer', 'NN')]


<FONT SIZE=4 COLOR="red"> Observación: </FONT>

### Etiquetador basado en Expresiones Regulares

- Las expresiones regulares nos permiten especificar cadenas de texto.

- Esta nos permite identificar patrones en las palabras para poderlas clasificar

- Vamos a crear nuestra propia lista para etiquetar. (tagging)

- El primer elemento es la expresión regular y la segunda la categoría gramatical.

- Usamos la instrucción **RegexpTagger**.

- Este ejemplo lo haremos en inglés

Usaremos Raw String Notation *(r"texto")* : una forma en la cual Python nos permite implementar expresiones regulares.



Veamos un par de ejemplos

In [ ]:
pattern = [(r"He", "TAG")]
tagger=nltk.RegexpTagger(pattern)

print(tagger.tag("He was born He in March 1991".split()))

[('He', 'TAG'), ('was', None), ('born', None), ('He', 'TAG'), ('in', None), ('March', None), ('1991', None)]


In [ ]:
patrones = [(r"[Aa]m$", "Verb-to-be"),
            (r".*ly$", "adverb"),
            (r"[Ww]ere", "Verb-to-be-past"),
            (r"[Tt]hey$", "pron"),
            (r".*ing$", "gerun"),
            (r'.*ed$', 'simple past')]
tagger=nltk.RegexpTagger(patrones)
print(tagger.tag("They were playing soccer fastly . I am happy".split()))

[('They', 'pron'), ('were', 'Verb-to-be-past'), ('playing', 'gerun'), ('soccer', None), ('fastly', 'adverb'), ('.', None), ('I', None), ('am', 'Verb-to-be'), ('happy', None)]


In [ ]:
print(nltk.pos_tag("They were playing soccer fastly . I am happy".split()))

[('They', 'PRP'), ('were', 'VBD'), ('playing', 'VBG'), ('soccer', 'NN'), ('fastly', 'RB'), ('.', '.'), ('I', 'PRP'), ('am', 'VBP'), ('happy', 'JJ')]


# <FONT SIZE=5 COLOR="purple"> Bag of Words </FONT>

- *Bag of Words* o ***Bolsa de Palabras*** (***BoW***) es un modelo que se utiliza para simplificar el contenido de un documento (o conjunto de documentos) omitiendo la gramática y el orden de las palabras, centrándose solo en el número de ocurrencias de palabras dentro del texto (o corpus).



In [ ]:
documento = ["carlos juega mucho carlos carlos carro carro juega universidad universidad juega juega  mucho mucho carlos",
             "conduce conduce conduce carro carro mucho mucho carro carro carro carro carro",
             "universidad universidad MACC MACC MACC MACC MACC MACC UR UR UR UR UR UR UR",
             "universidad universidad universidad carlos carlos conduce conduce carlos carlos carlos UR UR UR UR",
             "universidad universidad carlos carlos carlos conduce conduce carro carro carro carro mucho mucho mucho",
             "carlos juega universidad carro mucho juega mucho"]

A continuación creamos una bolsa de palabras con las frecuencias.

In [ ]:
# Construimos la bolsa de palabras
bow = dict()
for doc in documento:
    doc = doc.split(" ")
    for palabra in doc:
        if palabra in bow:
            bow[palabra] += 1
        else:
            bow[palabra] = 1
print(bow)

{'carlos': 13, 'juega': 6, 'mucho': 10, 'carro': 14, 'universidad': 10, '': 1, 'conduce': 7, 'MACC': 6, 'UR': 11}


**Ejercicio en clase:**

Utilice la librería ***nltk*** para generar en una línea de código el resultado anterior.

Existen más formas de construir bolsas de palabras. Las más utilizadas son las siguiente:

  1. Vectores de Frecuencias (TF)
  2. One-Hot-Encode
  3. Term Frequency-Inverse Document Frequency (TF-IDF)
    
Vamos a abordar cada una de las anteriores formas y utilizaremos las siguientes librerías para su implementación.

  * ***scikit***
  * ***NLTK***
  * ***Gensim***

¿Por qué es necesario conocer las tres?

La respuesta a esta pregunta radica en que hay librerías especializadas para determinados modelos, y en general, debemos hacer una bolsa de palabras antes de aplicar algunos modelos. Por ejemplo, *Gensim* es muy usada para toping-modeling y LDA, etc.
    



### -Scikit

* Esta librería devuelve una matriz en la que las **filas representan a cada documento del corpus** y las **columnas el número de apariciones de las palabras**.


* Para saber que palabra corresponde a cada columan de la matriz, scikit nos devuelve una lista en la que coinciden los indice de cada una de las palabras de la lista con la matriz.


* Para más información ver el siguiente enlace: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

## <FONT SIZE=5 COLOR="blue"> 1. Vectores de Frecuencias </FONT>

- Los ***vectores de frecuencias*** es el método más sencillo de construir las ***Bolsas de Palabras***.

- Simplemente consiste en contar cuantas veces aparece una palabra en el documento del corpus.

In [ ]:
# para hacer TF en sklearn
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(documento)

# Resultados
print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['carlos' 'carro' 'conduce' 'juega' 'macc' 'mucho' 'universidad' 'ur']
[[4 2 0 4 0 3 2 0]
 [0 7 3 0 0 2 0 0]
 [0 0 0 0 6 0 2 7]
 [5 0 2 0 0 0 3 4]
 [3 4 2 0 0 3 2 0]
 [1 1 0 2 0 2 1 0]]


### Gensim

* ***Gensim trabaja con "Diccionarios"*** (gensim.corpora.Dictionary) que es una estructura de datos en la que guarda el orden de las palabras que hay en el corpus.


* Posteriormente se construye la Bolsa de Palabras con las frecuencias con la función "***doc2bow***"


* Como resultado devuelve una lista por cada documento en la que se indicida por cada palabra del documento identificada por el 'id' del diccionario previamente construido la frecuencia de esa palabra en el documento.


* Para más información ver el siguiente enlace: https://radimrehurek.com/gensim/corpora/dictionary.html

In [ ]:
import gensim
# primero tokenizamos
tokenize = [nltk.word_tokenize(text) for text in documento]
# creamos un diccionario
dictionary = gensim.corpora.Dictionary(tokenize)
# utilizamos doc2bow
vectors = [dictionary.doc2bow(token) for token in tokenize]

# codigos de las palabras
print(dictionary.token2id)
# frecuencias
print('\nApariciones de las palabras en los documentos:')
vectors

{'carlos': 0, 'carro': 1, 'juega': 2, 'mucho': 3, 'universidad': 4, 'conduce': 5, 'MACC': 6, 'UR': 7}

Apariciones de las palabras en los documentos:


[[(0, 4), (1, 2), (2, 4), (3, 3), (4, 2)],
 [(1, 7), (3, 2), (5, 3)],
 [(4, 2), (6, 6), (7, 7)],
 [(0, 5), (4, 3), (5, 2), (7, 4)],
 [(0, 3), (1, 4), (3, 3), (4, 2), (5, 2)],
 [(0, 1), (1, 1), (2, 2), (3, 2), (4, 1)]]

## <FONT SIZE=5 COLOR="blue"> 2. (TF) One-Hot-Encode </FONT>

- Este método de construcción de la Bolsa de Palabras consiste en indicar con un flag ([0,1], [True, False], etc.) si una palabra aparece o no en el documento.

Para más información ver el siguiente enlace: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Binarizer.html#sklearn.preprocessing.Binarizer

In [ ]:
# para genetar one-hot.encode con sklearn

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import Binarizer

vectorizer = CountVectorizer()
corpus = vectorizer.fit_transform(documento)

onehot = Binarizer()
corpus = onehot.fit_transform(corpus.toarray())

# Resultados
print(vectorizer.get_feature_names_out())
print(corpus)

['carlos' 'carro' 'conduce' 'juega' 'macc' 'mucho' 'universidad' 'ur']
[[1 1 0 1 0 1 1 0]
 [0 1 1 0 0 1 0 0]
 [0 0 0 0 1 0 1 1]
 [1 0 1 0 0 0 1 1]
 [1 1 1 0 0 1 1 0]
 [1 1 0 1 0 1 1 0]]


In [ ]:
# Para hacerlo en nltk
import nltk

def tokenize(text):
    for token in nltk.word_tokenize(text):
        yield token

def vectorize(corpus):
    return {token: True for token in tokenize(corpus)}

vectors = map(vectorize, documento)

# Resultados
for v in vectors:
    print(v)

{'carlos': True, 'juega': True, 'mucho': True, 'carro': True, 'universidad': True}
{'conduce': True, 'carro': True, 'mucho': True}
{'universidad': True, 'MACC': True, 'UR': True}
{'universidad': True, 'carlos': True, 'conduce': True, 'UR': True}
{'universidad': True, 'carlos': True, 'conduce': True, 'carro': True, 'mucho': True}
{'carlos': True, 'juega': True, 'universidad': True, 'carro': True, 'mucho': True}


**Nota:** En Gensim, la estructura de salida es la misma que en el caso de la construcción de la Bolsa de Palabras de frecuencias salvo que los valores de las palabras en los documentos solo tendrán valor $1$.

Para más información ver el siguiente enlace:

https://radimrehurek.com/gensim/corpora/dictionary.html

In [ ]:
import gensim

tokenize = [nltk.word_tokenize(text) for text in documento]
dictionary = gensim.corpora.Dictionary(tokenize)
vectors = [[(token[0], 1) for token in dictionary.doc2bow(doc)] for doc in tokenize]

# codificación
print(dictionary.token2id)
# bolsa de palabras
print('\nApariciones de las palabras en los documentos (id, 1):')
vectors

{'carlos': 0, 'carro': 1, 'juega': 2, 'mucho': 3, 'universidad': 4, 'conduce': 5, 'MACC': 6, 'UR': 7}

Apariciones de las palabras en los documentos (id, 1):


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)],
 [(1, 1), (3, 1), (5, 1)],
 [(4, 1), (6, 1), (7, 1)],
 [(0, 1), (4, 1), (5, 1), (7, 1)],
 [(0, 1), (1, 1), (3, 1), (4, 1), (5, 1)],
 [(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)]]

## <FONT SIZE=5 COLOR="blue"> 3. Term Frequency-Inverse Document Frequency (TF-IDF) </FONT>

- El TF-IDF (Frecuencia de Termino - Frecuencia Inversa de Documento) es una medida numérica que permite expresar como de relevante es una palabra para un documento en una colección de documentos (o corpus).

- La fórmula que se aplica es

$$idf(t_i) = \log \left (\dfrac{N}{n_i} \right)$$

donde

  - $t_i$ es el término $i$.
  - $n_i$ es número de documentos donde aparace el termino $i$.
  - $N$ número de documentos.


## <FONT SIZE=3 COLOR="blue"> Motivación de TF+iDF </FONT>

- **Referencia de consulta:** Understanding Inverse Document Frequency:
On theoretical arguments for IDF. Stephen Robertson. Microsoft Research.

- En el campo de la información, la **entropía** (Shannon) mide la incertidumbre de una fuente de información.

- También se puede decir, que es la información promedio que contienen los símbolos usados.

- En ese orden de ideas, las palabras que son más frecuentes aportan menos información. (el, a de, que). Si uno las quita de un documento, podría entender más de este que si quita una palabra que se repita menos.

- La ley de **Zipf**: es una regla empírica que indica que la frecuencia de aparición de distintas palabras sigue una distribución que es aproximadamente

$$P_n \approx \dfrac{1}{a^n}$$

donde, $P_n$ es la frecuencia de la n-ésima palabra más frecuente y $a>1$.

- La entropía termodinámica es igual a la entropía de la teoría de la información de esa distribución (medida usando el logaritmo neperiano) multiplicada por la constante de Boltzmann k. $k\log N$.

- Supongamos que tenemos un evento con grado de indeterminación $k$ o en otras palabras, que existen k estados posibles y todos son equiprobables. Luego

$$probabilidad(ocurrencia) = \dfrac{1}{k}$$.

$$P(t_i)= \dfrac{n_i}{N}$$
$$idf(t_i) = - \log (P(t_i)) = \log (\dfrac{N}{n_i})$$

Veamos las dos definiciones de manera precisa:

***Frecuencia del Término (Frequency Term-TF):***

- Es la frecuencia de una palabra en cada documento del corpus.

- Relación entre el número de veces que aparace la palabra en el documento comparada con el total de palabras de ese documento.

$$TF(i,j) = tf_{ij}= \dfrac{n_{i,j}}{\sum_\limits{j} n_{i,j}}  $$

$$tf_{ij}=\dfrac{\text{# de apariciones de la palabra j}}{\text{total de palabras en el documento i}}$$

donde:

- $tf_{i,j}$: es la frecuencia (relativa) de la palabra $j$ en el documento $i$

- $n_{i,j}$: es el número de veces que aparece la palabra $j$ en el documento $i$.

***Frecuencia inversa de documento (Inverse Document Frequency iDF):***

- Es una medida que permite calcular el peso de las palabras en los documentos del corpus.

- Si una palabra no aparece en mucho documentos su $iDF$ debe ser alto, comparada con una que aparezca en más documentos.

$$idf(t_j) = \log \left (\dfrac{N}{n_j} \right)$$

donde

  - $t_j$ es una palabra del corpus
  - $n_j$ es número de documentos donde aparace el término o palabra $j$.
  - $N$ número de documentos.


 ***Fórmula TF+iDF***

 $$TF+iDF(t_j) = tf(t_j)*idf(t_j)$$

$$ tf(t_j)*idf(t_j) =\dfrac{\text{# de apariciones de la palabra $t_j$ en el documento i}}{\text{total de palabras en el documento i}} * \dfrac{\text{ total de documentos en el corpus}}{\text{# de documentos donde aparace la palabra $t_j$}}  $$


**Observaciones**

- Construir la Bolsa de Palabras con TF-IDF en vez de con frecuencias evita dar "importancia" a texto muy largos y con mucha repetición de palabras, frente a textos cortos y con pocas repeticiones de palabras.

- En la literatura también podemos encontrarla en escala logarítmica así: También se puede definir de la siguiente manera

* ***TF*** (Term Frecuency): Es la frecuencia con la que aparece la palabra en un documento del corpus. Esta se define como:
    
    $$tf(t,d) = 1 + log(f_{t,d})$$
    
* ***IDF*** (Inverse Document Frequency): La frecuencia inversa del documento nos indica lo común que es una palabra en el corpus.
    
    $$idf(t,D) = log(1 + \frac{N}{n_t})$$
    
* ***TF-IDF*** queda definido como:
$$tfidf(t,d,D) = tf(t,d) \cdot idf(t,D)$$

**Implementación:**

* Las implementaciones del ***TF-IDF*** de **Scikit** y **Gensim** estan pensadas para corpus con un número relevante de documentos y de palabras, por tanto la implementación del ***TF-IDF*** acepta una serie de parámetros para no tener en cuenta Stop Words, palabras irrelevantes, etc. por lo que si se realiza una implementación del ***TF-IDF*** según la bibliografia no van a conincidir los resultados de esa implementación con los resultados de las librerías de **Scikit** y **Gensim** a no ser que se modifiquen los parámetros de las funciones del ***TF-IDF***.


Scikit

* Las estructuras de datos de salida de ***Scikit*** son iguales de en el caso de la construcción del vector de frecuencias salvo que en el contenido de la matriz será de números decimales en vez de números enteros.


* Para más información ver el siguiente enlace: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html



- Veamos un ejemplo dado el siguiente corpus de 3 documentos con las siguientes palabras:

```
corpus = ["messi messi jordan",
          "jordan messi carro jordan carro",
          "avión messi mesa"]
```
$$$$
<center>
<table class="default">
<tr>
    <th scope="row">TF</th>
    <th>messi</th>
    <th>jordan</th>
    <th>carro</th>
    <th>avión</th>
    <th>mesa</th>
</tr>
<tr>
    <th>$d_1$</th>
    <th>$\dfrac{2}{3}$</th>
    <th>$\dfrac{1}{3}$</th>
    <th>$0$</th>
    <th>$0$</th>
    <th>$0$</th>
</tr>
<tr>
    <th>$d_2$</th>
    <th>$\dfrac{1}{5}$</th>
    <th>$\dfrac{2}{5}$</th>
    <th>$\dfrac{2}{5}$</th>
    <th>$0$</th>
    <th>$0$</th>
</tr>
<tr>
    <th>$d_3$</th>
    <th>$\dfrac{1}{3}$</th>
    <th>$0$</th>
    <th>$0$</th>
    <th>$\dfrac{1}{3}$</th>
    <th>$\dfrac{1}{3}$</th>
</tr>
</table>
</center>

- Por ejemplo. La frecuencua de *messi* en el documento 1 es

$$TF_{11}=d_1(messi) = \dfrac{2}{3}$$

$$TF_{24}=d_2(avión) = 0$$

Ahora, veamos $idf$

$$$$
<center>
<table class="default">
<tr>
    <th scope="row">TF+iDF</th>
    <th>--messi--   </th>
    <th>--jordan--  </th>
    <th>--carro--   </th>
    <th>--avión--   </th>
    <th>--mesa--    </th>
</tr>

<tr>
    <th>$idf$</th>
    <th>$log \left(\dfrac{3}{3}\right)$</th>
    <th>$log \left(\dfrac{3}{2}\right)$</th>
    <th>$log \left(\dfrac{3}{1}\right)$</th>
    <th>$log \left(\dfrac{3}{1}\right)$</th>
    <th>$log \left(\dfrac{3}{1}\right)$</th>
</tr>



<tr>
    <th>$d_1$</th>
    <th>$0$</th>
    <th>$0.06$</th>
    <th>$0$</th>
    <th>$0$</th>
    <th>$0$</th>
</tr>
<tr>
    <th>$d_2$</th>
    <th>$0$</th>
    <th>$0.07$</th>
    <th>$0.19$</th>
    <th>$0$</th>
    <th>$0$</th>
</tr>
<tr>
    <th>$d_3$</th>
    <th>$0$</th>
    <th>$0$</th>
    <th>$0$</th>
    <th>$0.16$</th>
    <th>$0.16$</th>
</tr>
</table>
</center>

Por ejemplo

$$df-idf(2,3) = tf(2,3)*idf(2,3)=\dfrac{2}{5}*\log(3)=0.19$$

*Análisis de la tabla:*

- La palabra *messi* tiene valor 0 ya que está en los tres documentos, esto quiere decir que no aporta información relevante para discriminar los documentos o identificar a los mismos.

- Las palabras *avión* , *carro* y *mesa* tienen valores altos ya que sus frecuencias de aparación entre documentos es baja.



In [ ]:
corpus = ["messi messi jordan",
          "jordan messi carro jordan carro",
          "avión messi mesa"]

Vamos a calcular **TF+iDF** con las librerías que hemos venido trabajando

### -Gensim

* La estructura de datos de salida de ***Gensim*** es la misma que en el caso de la construcción de la Bolsa de Palabras de frecuencias salvo que los valores de las palabras en los documentos tendrán números decimales en vez de números enteros.


* Para más información ver el siguiente enlace: https://radimrehurek.com/gensim/models/tfidfmodel.html

In [ ]:
import gensim

tokenize = [nltk.word_tokenize(text) for text in corpus]
dictionary = gensim.corpora.Dictionary(tokenize)
tfidf = gensim.models.TfidfModel(dictionary=dictionary, normalize=True)
vectors = [tfidf[dictionary.doc2bow(doc)] for doc in tokenize]

# Resultados
print('Diccionario de palabras -> palabra: id\n')
print(dictionary.token2id)
print('\nApariciones de las palabras en los documentos (id, tfidf):')
vectors

Diccionario de palabras -> palabra: id

{'jordan': 0, 'messi': 1, 'carro': 2, 'avión': 3, 'mesa': 4}

Apariciones de las palabras en los documentos (id, tfidf):


[[(0, 1.0)],
 [(0, 0.34624155305796134), (2, 0.9381453975456102)],
 [(3, 0.7071067811865475), (4, 0.7071067811865475)]]

Observe que lo anterior indica que:

- Apesar de que *messi* tiene una mayor frecuencia en el primer documento no es la más relevante o característica del texto.

- En el documento 2, la palabra más relevante es *carro*.

- En el documento 3 hay dos palabras con igual relevancia o claves del texto.

A continuación, otras formas de cálcular *TF+iDF*

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(min_df=1)

# Pasamos los tweets normalizados a Bolsa de palabras
X = tfidf.fit_transform(corpus)
X
# Resultados
print(tfidf.get_feature_names_out ())
print(X.toarray())

['avión' 'carro' 'jordan' 'mesa' 'messi']
[[0.         0.         0.54134281 0.         0.84080197]
 [0.         0.77484319 0.58928822 0.         0.22881744]
 [0.65249088 0.         0.         0.65249088 0.38537163]]


In [ ]:
feature_names = tfidf.get_feature_names_out()
for col in X.nonzero()[1]:
    print (feature_names[col], ' - ', X[0, col])

jordan  -  0.5413428136679054
messi  -  0.8408019731721111
carro  -  0.0
jordan  -  0.5413428136679054
messi  -  0.8408019731721111
mesa  -  0.0
avión  -  0.0
messi  -  0.8408019731721111


Finalmente, un ejemplo con la variable documento definida inicialmente.

In [ ]:
import numpy as np
import pandas as pd

## <FONT SIZE=3 COLOR="blue"> Ejercicio en clase </FONT>

Considere el corpus que se da a continuación:

1. Normalice el corpus.
  
   - convierta a minúscula ( Fabian ---> fabian)
   - reemplace las tildes ( acción---> accion)
   - Quitar signos de puntuación y caracteres especiales (Hola!---hola)
   - Elimine las stop-words.

2. Aplique la función ***TfidfVectorizer(min_df=1)***

3. Seleccione las cinco palabras claves de cada documento.

   

In [52]:
import re
import string
from bs4 import BeautifulSoup
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from urllib.request import urlopen

In [ ]:
corpus=["Las matemáticas son una de las ciencias más antiguas. Floreció primero antes de la antigüedad en Mesopotamia, 19​ En cuanto a la geometría20​, India y China, y más tarde en la antigüedad en Grecia y el helenismo. De ahí data la orientación hacia la tarea de demostración puramente lógica y la primera axiomatización, a saber, la geometría euclidiana20​. En la Edad Media sobrevivió de forma independiente en el primer humanismo de las universidades y en el mundo árabe.",
           "La guerra es la forma de conflicto sociopolítico más grave entre dos o más grupos humanos. Se da tanto en sociedades tribales como en civilizadas, pero es más grave entre estas últimas ya que son más complejas, masificadas y tecnificadas. Es quizás la más antigua de las relaciones internacionales y ya en el comienzo de las civilizaciones se constata el enfrentamiento organizado de grupos humanos armados con el propósito de controlar recursos naturales o humanos (conflictos entre cazadores nómadas y recolectores sedentarios que sí desarrollaron el concepto de propiedad),3​ exigir un desarme o imponer algún tipo de tributo, ideología, nacionalidad o religión, sometiendo, despojando y, en su caso, destruyendo al enemigo. Es más, este tipo de conducta gregaria es extensible a la mayor parte de los homínidos4​ y se encuentra estrechamente relacionado con el concepto etológico de territorialidad.",
           "La biología se ocupa tanto de la descripción de las características y los comportamientos de los organismos individuales, como de las especies en su conjunto, así como de las relaciones entre los seres vivos y de las interacciones entre ellos y el entorno. De este modo, trata de estudiar la estructura y la dinámica funcional comunes a todos los seres vivos, con el fin de establecer las leyes generales que rigen la vida orgánica y los principios de ésta.6​",
           "Las ciencias de la computación o ciencias de la informática son las ciencias formales que abarcan las bases teóricas de la información y la computación, así como su aplicación en los sistemas informáticos.1​2​3​ El cuerpo de conocimiento de las ciencias de la computación es frecuentemente descrito como el estudio sistemático de los procesos algorítmicos que describen y transforman información: su teoría, análisis, diseño, eficiencia, implementación, algoritmos sistematizados y aplicación.4​ En términos más específicos se trata del estudio sistemático de la factibilidad, estructura, expresión y mecanización de procedimientos metódicos (o algoritmos) que subyacen en la adquisición, representación, procesamiento, almacenamiento, comunicación y acceso a la información. La información puede estar codificada en forma de bits en una memoria de computadora, o en algún otro objeto, como los genes y proteínas en una célula biológica.5​",
           "Una avión de caza, avión de combate, avión de guerra, o simplemente caza,1​ es una aeronave militar diseñada fundamentalmente para la guerra aérea con otras aeronaves, en oposición a los bombarderos, que están diseñados principalmente para atacar objetivos terrestres mediante el lanzamiento de bombas. Los cazas son pequeños, veloces y de gran maniobrabilidad. Muchos cazas poseen capacidades secundarias de ataque a tierra, y algunos son de doble propósito para actuar como cazabombarderos, término también usado para nombrar a los aviones de ataque a tierra con capacidades de caza.",
          "La gramática es el estudio de las reglas y principios que gobiernan el uso de las lenguas y la organización de las palabras dentro de unas oraciones y otro tipo de constituyentes sintácticos. También se denomina así al conjunto de reglas y principios que gobiernan el uso de una lengua concreta; así, cada lengua tiene su propia gramática.A veces se restringe el uso del término gramática a las reglas y principios que definen la morfología y la sintaxis. Sin embargo, la separación de los niveles no es totalmente nítida por diversas razones, como que ciertas reglas gramaticales se realizan en el nivel fonético-fonológico, o que existen parámetros o criterios semánticos que sirven para decidir cuándo una determinada construcción se considera gramatical. Algunas tendencias de la lingüística moderna representan un regreso a los temas de la gramática tradicional desde nuevos puntos de vista"
          "Un volcán (del nombre del dios mitológico romano Vulcano) es una estructura geológica por la que emerge el magma que se divide en lava y gases provenientes del interior de la Tierra. El ascenso del magma ocurre en episodios de actividad violenta denominados erupciones, que pueden variar en intensidad, duración y frecuencia, desde suaves corrientes de lava hasta explosiones extremadamente destructivas. En ocasiones, los volcanes adquieren una forma cónica por la acumulación de material de erupciones anteriores. En la cumbre se encuentra su cráter o caldera.",
          "El punto de origen de un terremoto se denomina foco o hipocentro, a partir de allí se propaga en forma de ondas sísmicas. El punto de la superficie terrestre que se encuentra más cerca del hipocentro, donde alcanzan en primer lugar las ondas sísmicas se llama epicentro. Dependiendo de su magnitud y origen, un terremoto puede causar desplazamientos de la corteza terrestre, corrimientos de tierras, maremotos (o también llamados tsunamis) o actividad volcánica. Para medir la energía que fue liberada por un terremoto se emplean diversas escalas, entre ellas, la escala de Richter que es la más conocida y utilizada por los medios de comunicación.",
          "La palabra mar también se usa para indicar secciones más pequeñas del océano, en parte interiores, y para algunos grandes lagos salados, totalmente interiores, como el mar Caspio, el mar Muerto o el mar de Aral. Se habla entonces de mar cerrado o interior, aunque el término correcto sería el de lago endorreico.",
          "Rusia es el país que limita con mayor número de países, un total de dieciséis,n. 5​ y el que tiene las fronteras más extensas. Limita con los siguientes países (empezando por el noroeste y siguiendo el sentido antihorario): Noruega, Finlandia, Estonia, Letonia, Bielorrusia, Lituania,n. 6​ Polonia,n. 6​ Ucrania,n. 7​ Georgia,n. 8​ Azerbaiyán, Kazajistán, República Popular China, Mongolia y Corea del Norte. Tiene límites de aguas territoriales con varios de los anteriores, con Japón y con Estados Unidos (en concreto, con el estado de Alaska). Limita también con los Estados de reconocimiento limitado Abjasia y Osetia del Sur y con las repúblicas de Donetsk y Lugansk, reclamadas y parcialmente controladas por la propia Rusia. Sus costas están bañadas por el océano Glacial Ártico, el norte del océano Pacífico y mares interiores como el Báltico, el Negro y el Caspio." ]

In [ ]:
# identificar las 5 palabras claves del documento

In [53]:
# Definir la funcion
def cleanPLN(text, language='spanish'):
    # Pasar a minúsculas
    text = text.lower()

    # Remover etiquetas HTML
    text = BeautifulSoup(text, 'html.parser').get_text()

    # Remover caracteres especiales y puntuación
    text = re.sub(r'[^\w\s]', '', text)

    # Tokenizar
    tokens = word_tokenize(text)

    # Eliminar stop words
    stop_words = set(stopwords.words(language))
    tokens = [word for word in tokens if word not in stop_words]

    # Dejar palabras con más de 3 caracteres
    tokens = [word for word in tokens if len(word) > 3]

    # Regresar la cadena de texto simplificada
    cleaned_text = ' '.join(tokens)

    return cleaned_text

In [54]:
corpus = [cleanPLN(texto) for texto in corpus]

In [60]:
corpus

['matematicas ciencias antiguas florecio primero antiguedad mesopotamia cuanto geometria20 india china tarde antiguedad grecia helenismo data orientacion hacia tarea demostracion puramente logica primera axiomatizacion saber geometria euclidiana20 edad media sobrevivio forma independiente primer humanismo universidades mundo arabe',
 'guerra forma conflicto sociopolitico grave grupos humanos sociedades tribales civilizadas grave ultimas complejas masificadas tecnificadas quizas antigua relaciones internacionales comienzo civilizaciones constata enfrentamiento organizado grupos humanos armados proposito controlar recursos naturales humanos conflictos cazadores nomadas recolectores sedentarios desarrollaron concepto propiedad3 exigir desarme imponer algun tipo tributo ideologia nacionalidad religion sometiendo despojando caso destruyendo enemigo tipo conducta gregaria extensible mayor parte hominidos4 encuentra estrechamente relacionado concepto etologico territorialidad',
 'biologia ocu

In [70]:
tfidf = TfidfVectorizer(min_df=1)
X = tfidf.fit_transform(corpus)

In [69]:
for i in range(len(corpus)):
  U = pd.DataFrame(X.toarray()[i],
                   index = tfidf.get_feature_names_out,
                   columns=["TF+iDF"])
  print("Documento",i)
  print(U.sort_values("TF+iDF")[::-1].head(5))

TypeError: ignored